export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const DEFAULT_RETURN = 'DEFAULT_RETURN';
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const POST_CRUD = "POST_CRUD";
export const REQUEST_INIT = "REQUEST_INIT";
export const IDLE_LOGOUT = "IDLE_LOGOUT";